### ISSUE TITLE
artifacting around text in front of mr-img

### ISSUE THREAD

**Issue by michaelthatsit** [Volumetrics-io/mrjs#257]
<img width="1249" alt="Screenshot 2024-01-16 at 5 33 32 PM" src="https://github.com/Volumetrics-io/mrjs/assets/19628643/79c48140-610b-4444-ac60-d5bd3957ac46">

I assumed this was something to do with antialiasing, but I think this popped up around the time masking landed.

**Comment by hanbollar** [comment]
@michaelthatsit - is this still open? i think we stated this was resolved from the object change you had done with mr text and textObj in terms of nexting

lmk if not though and i can look back into this at some point

**Comment by michaelthatsit** [comment]
This is still an issue, the previous fix resolved the masking issue. not the weird artifacting.

**Comment by hanbollar** [comment]
gotcha

**Comment by hanbollar** [comment]
rechecked in office - all good to close ~
