### ISSUE TITLE
quick discussion on render order

### ISSUE THREAD

**Issue by hanbollar** [Volumetrics-io/mrjs#480]
@michaelthatsit I'm happy if you explain because as I explained at other places I'm thinking of using `renderOrder` for masking (stencil) system.

Anyways, this is just a question, not a comment for any blocking issue.

_Originally posted by @takahirox in https://github.com/Volumetrics-io/mrjs/pull/464#discussion_r1509894813_

-------------

opening a new issue here so the conversation doesnt get bogged down by the noise in the other pr

@michaelthatsit - could you give an explanation of our current use of renderOrder? just want to make sure it works with how takahiro's planning to use it for masking

**Comment by takahirox** [comment]
I'm still want to know our renderOrder usage, however the priority is low now. I was thinking of using renderOrder for masking system but I implemented another approach #492

**Comment by michaelthatsit** [comment]
We're using render order for environment clipping. 

Hands and MRPlanes have a renderOrder set to 0 and colorWrite set to false, and everything else has a renderOrder > 0 so that they still appear to be behind "invisible" objects. 

We could enum these for clarity. Something like

```
RenderOrder {
    Environment: 0,
    Default: 1,
    ???
}

```

Obviously we could still utilize renderOrder in other ways as long as it's clear that 0 is reserved for physical object occlusion.

**Comment by takahirox** [comment]
Closing because @michaelthatsit explained, thanks. We should open more specific issues when needed for renderOrder related topic.
